apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050              #this is used in inter pod communication
      targetPort: 3000        #this is the port of pod on which container is running
      nodePort: 31515         #This is the port from where external world will communicate
  selector:
    component: web
