sudo: required
services:
  - docker

before_install:
  - docker build -t shiva0808/docker-react -f Dockerfile.dev

script:
  #- docker run shiva0808/docker-react npm run test -- --coverage
  - docker run -e CI=true shiva0808/docker-reach npm run test

  #-- --coverage is a node command to get out of test module with test output

deploy:
  provide: elasticbeanstalk
  region: "us-west-2"         #check from application URL from EBS
  app: "react-app"            #name of EBS app given
  env: "Docker-env"           #this is application environment name from EBS
  bucket_name: "elasticbeanstalk-us-west-2-30647661234" #check in aws S3
  bucket_path: "react-app"  #its created after first deployment so name it as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY      #this is updated, old method is comments in bottom
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
  
