sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git REV-PARSE HEAD)       #environment variable definition to get SHA of commited GIT repo
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  #- openssl aes-256-cbc -K $encrypted_0c35eeb_key -iv $encrypted
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project skilful-bern-214822     #this is project ID not name in GC
  - gcloud config set compute/zone us-central1-a        #Cluster zone name
  - gcloud container clusters get-credentials multi-cluster   #cluster name
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#above line defines environment vars to login docker, these environment vars needs
#to be added in travis project setting and will be picked
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
#  -docker run stephengrider/react-test npm run test -- --coverage
  -docker run -e CI=true stephengrider/react-test npm run test

#Download travis CI CLI to add encrypted file downloaded from Google Account Service

deploy:
  provider: script
  script: bash .deploy.sh
  on:
    branch: master
