-
  name: Install Softwares
  host: web
  vars:
    packages:
      - name: nginx
        required: true
      - name: mysql
        required: true
      - name: apache
        required: false
  tasks:
    name: 'installing {{item.name}} on Linux'
    yum:
      name: '{{item.name}}'
      state: present
    when: item.required == true
    loop: "{{packages}}"
