apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


#accessModes
#ReadWriteOnce       #Can be used by single node
#ReadOnlyMany         Multiple nodes can read from this
#ReadWriteMany        can be read and written to by many nodes
# kubectl get storageclass
# kubectl describe storageclass
