apiVersion: app/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:                        #this is persistent volume configuration
        - name: postgres-storage
          persistent-volume-claim:
            claimName: database-persistent-volume-claim   #this is coming from database-persistent-volume-claim.yaml
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:                   #this is mapping container with volume
            - name: postgres-storage      #this is coming from volumes section
              mountPath: /var/lib/postgressql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD     #this env variable help override default postgres password
              valueFrom:
                secretKeyRef:
                  name: pgpassword      #name of secret
                  key: PGPASSWORD       #key defined in secret

#Secret generated from below method
#kubectl create secret generic pgpassword --from-literal PGPASSWORD=1234asdf
#kubectl get secrets
