apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 5         #Code updated to increase number of pods to 5
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-worker   #updated image also
          ports:
            - container-Port: 9999      #This change in not possible in pod as object
