sudo: required
service:
  - docker

before_install:
  - docker build -t shiva0808/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run shiva0808/react-test npm run test -- --coverage
  - docker run -e CI=true shiva0808/react-test npm run test

after_success:
  - docker build -t shiva0808/multi-client ./client
  - docker build -t shiva0808/multi-server ./server
  - docker build -t shiva0808/multi-worker ./worker
  - docker build -t shiva0808/multi-nginx ./nginx
    #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #push all images to docker hub
  - docker push shiva0808/milti-client
  - docker push shiva0808/multi-server
  - docker push shiva0808/multi-worker
  - docker push shiva0808/multi-nginx

deploy:
  edge: true                  #Mfix for issing bucket_name error
  provide: elasticbeanstalk
  region: "us-west-1"         #check from application URL from EBS
  app: "multi-docker"            #name of EBS app given
  env: "multidockerenv"           #this is application environment name from EBS
  bucket_name: "elasticbeanstalk-us-west-1-30647661234" #check in aws S3
  bucket_path: "docker-multi"  #its created after first deployment so name it as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY      #this is updated, old method is comments in bottom
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
